### ISSUE TITLE
Problem with SignIn in android.

### ISSUE THREAD

**Issue by sumit26-code** [CodetrixStudio/CapacitorGoogleAuth#110]
Hello everyone!
I upgraded by application from capacitor 2 to capacitor 3.
Now, I am facing issue with google login.

I am using @codetrix-studio/capacitor-google-auth": "3.0.1" plugin for this.
And I am getting the following issue in android, for web its working fine for me.

Screenshot 2021-06-04 at 5 46 56 PM

**Comment by dotnetdreamer** [comment]
I am having same issue

**Comment by dotnetdreamer** [comment]
I was facing same issue. My web was working but not Android. So here is what i did:

- In addition to creating credentials (OAuth Client ID) for web [https://console.cloud.google.com/apis/credentials](https://console.cloud.google.com/apis/credentials), i did also for Android
- Then i went to [https://console.firebase.google.com/u/](https://console.firebase.google.com/u/) and created and Android project and downloaded the **google-services.json** and copied to my **android -> app** folder. 
- I then ran `npx cap sync` and run the app and it started working

**Comment by sumit26-code** [comment]
> I was facing same issue. My web was working but not Android. So here is what i did:
> 
> * In addition to creating credentials (OAuth Client ID) for web https://console.cloud.google.com/apis/credentials, i did also for Android
> * Then i went to https://console.firebase.google.com/u/ and created and Android project and downloaded the **google-services.json** and copied to my **android -> app** folder.
> * I then ran `npx cap sync` and run the app and it started working
>   ![image](https://user-images.githubusercontent.com/10280821/120890135-ea257880-c611-11eb-9751-9a0211c491ec.png)
> 
> **Firebase Console:**
> ![image](https://user-images.githubusercontent.com/10280821/120890199-235de880-c612-11eb-8cf4-e530db682a16.png)

Hi @dotnetdreamer 
I follow the same steps but nothing works out for me.

**Comment by fannyfan414** [comment]
Tried all combinations of both android client id and web client id - nothing works

**Comment by dotnetdreamer** [comment]
Can u make a sample so we can check it out ?

**Comment by fannyfan414** [comment]
> Can u make a sample so we can check it out ?

if you have working solution, please record step by step video or text guide with screens

**Comment by jonit-dev** [comment]
It was working fine on Capacitor 2 before the upgrade. Now I'm receiving this error for Android. Web is working fine, so I don't assume it's a credential issue (otherwise it would be bugged too?)

Please, help

**Comment by jonit-dev** [comment]
After wasting some hours of my life, I've come up with a solution. It would be great if the plugin docs covered all of this, on the main page.

Probably this is happening due to a SHA1 signature mismatch between your debug app (the one you're trying to run in emulator) and firebase.

To fix it on Android studio 4.2, click on Gradle tab (right side) and type **gradle signingReport**

This will output in a panel on the bottom left a SHA1 debug key, that you must add to your firebase project settings

Now open Firebase, and add it:
![image](https://user-images.githubusercontent.com/30300459/122661296-86389f00-d13d-11eb-90c3-5aab9fab350b.png)


Then try running your emulator again. It will probably work (I hope).

btw, my MainActivity.java is:
```package com.YOURAPPNAMEHERE.mobile;

import android.os.Bundle;
import com.getcapacitor.BridgeActivity;
import com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth;

public class MainActivity extends BridgeActivity {

     @Override
     public void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);

        registerPlugin(GoogleAuth.class);
     }

}
```

**Comment by sumit26-code** [comment]
> I was facing same issue. My web was working but not Android. So here is what i did:
> 
> * In addition to creating credentials (OAuth Client ID) for web https://console.cloud.google.com/apis/credentials, i did also for Android
> * Then i went to https://console.firebase.google.com/u/ and created and Android project and downloaded the **google-services.json** and copied to my **android -> app** folder.
> * I then ran `npx cap sync` and run the app and it started working
>   ![image](https://user-images.githubusercontent.com/10280821/120890135-ea257880-c611-11eb-9751-9a0211c491ec.png)
> 
> **Firebase Console:**
> ![image](https://user-images.githubusercontent.com/10280821/120890199-235de880-c612-11eb-8cf4-e530db682a16.png)

It works for me, thanks.

**Comment by NLueg** [comment]
The error after the migration from Capacitor 2 to 3 should be now fixed with the newer version.

**Comment by cwayfinder** [comment]
According to my error logs in Sentry, about 1% of my users face this error. This is very strange. How it can work on some devices and don't work on others?

**Comment by gugu** [comment]
They've released outdated code for Android in npm. Try to install this plugin from the master branch

**Comment by UTSOURCE** [comment]
I also encountered the same mistake, but I did according to the answers of others above, and still reported this mistake

**Comment by Read1337** [comment]
> After wasting some hours of my life, I've come up with a solution. It would be great if the plugin docs covered all of this, on the main page.
> 
> Probably this is happening due to a SHA1 signature mismatch between your debug app (the one you're trying to run in emulator) and firebase.
> 
> To fix it on Android studio 4.2, click on Gradle tab (right side) and type **gradle signingReport**
> 
> This will output in a panel on the bottom left a SHA1 debug key, that you must add to your firebase project settings
> 
> Now open Firebase, and add it: ![image](https://user-images.githubusercontent.com/30300459/122661296-86389f00-d13d-11eb-90c3-5aab9fab350b.png)
> 
> Then try running your emulator again. It will probably work (I hope).
> 
> btw, my MainActivity.java is:
> 
> ```
> 
> import android.os.Bundle;
> import com.getcapacitor.BridgeActivity;
> import com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth;
> 
> public class MainActivity extends BridgeActivity {
> 
>      @Override
>      public void onCreate(Bundle savedInstanceState) {
>          super.onCreate(savedInstanceState);
> 
>         registerPlugin(GoogleAuth.class);
>      }
> 
> }
> ```

This did fix the issues on the android emulator. But I still have issues with real devices. I added the sha1 from my .keystore but it doesn't work. I have the "somethign went worng" error.

**Comment by grallc** [comment]
Still facing the issue.
Everything was working perfectly before Capacitor 3.

I've triple checked every key, and everything is fine.

How can I fix/debug this ?
